### ISSUE TITLE
nary DAG support

### ISSUE THREAD

**Issue by refset** [mattbierner/neith#12]
I've spent the last couple of evenings thinking about how neith could be adapted to support nary directed acyclic graphs. I'm specifically attempting to build upon the nary.js example and at that level of abstraction it would seem (at first glance) like a trivial task to lookup a key within a ctx object "registry" during getChildren() and so reuse an existing ctx instead of naively creating a new ctx. However, I'm now fairly certain such a mechanism is impossible without re-engineering the underlying zipper.

Have you thought about this before? Is there an obvious way of achieving this that I'm missing?

**Comment by mattbierner** [comment]
I think there are two problems that you need to solve for this:

Defining an immutable graph structure. Neith is limited in that it only supports immutable data structures. This allows the implementation to make certain internal optimizations, and I've found that mutation in a zipper can often lead to unexpected behavior. I also reasoned that if you have a mutable data structure, you probably don't need a zipper in the first place.

A brief search turned up few ways to encode an immutable DAG, but most seem to boil to adding another layer of indirection. The simplest approach stores nodes externally in an immutable map (like the registry you mention), with unique ids as keys, and then expresses edges using the unique ids instead of the nodes themselves. (If you need a persistent map, here's one implementation: https://github.com/mattbierner/hamt )

Zippering a graph is something I'm less familiar with, but DAGs should be more simple than unrestricted graphs. I have a feeling that is should be pretty similar to the tree case, but I'm not positive on that.

Off the top of my head, something like this based on the tree zipper maybe:

```
var Dag = function(nodes, uid, currentNode) {
    this.nodes = nodes; // persistent map of uids to nodes
    this.uid = uid.
    this.currentNode = currentNode; // Current nodes store a value and edges pointing to uids.
};

// Only get edges
var getChildren = function(dag) {
     return Object.keys(dag.currentNode); // assume edges are encoded as properties on a node
};

// Get actual child value
var getChild = function(dag, child) {
    var targetNodeId = dag.currentNode[child];
    return new Dag(
       dag.nodes, // since there are no cycles, maybe you don't need to update the map here?
       targetNodeId,
       dag.nodes.get(targetNodeId));
};

// Reconstruct dag after edit
var construct = function(dag, pairs, values) {
    return new Dag(
        dag.nodes.update(dag.uid, newNode), // update entry in map
        dag.uid,
        reconstructNode(dag, pairs, values)); // rebuild the actual node object
};
```

**Comment by refset** [comment]
> if you have a mutable data structure, you probably don't need a zipper in the first place

Completely agreed.

I managed to get something satisfactory (for my needs!) working just by ~~modifying~~ butchering zipper.kep: https://github.com/jez0990/neith/commit/70ff88de616153054d52ddcfaaae4a16e70f1091

A couple of housekeeping things I should mention:
- I just updated my global khepri (using `npm install -g khepri`) but I had to do this to get it to run
  `mv /usr/lib/node_modules/khepri/node_modules/khepri-parse/node_modules/xregexp /usr/lib/node_modules/khepri/node_modules/khepri-parse/node_modules/XRegExp`
- After `npm run build-node` I had to manually add `var ops = arguments;` in a couple of places in the generated js (ops was being given as the name of the first argument instead)

Using hamt would be pretty nice but the immutable map is fine for now as my keys are value hashes. Working around the absence of array notation in khepri was fun!

Thanks for the sounding board :)

**Comment by mattbierner** [comment]
Glad you found something that works. Let me know if there are any additions or changes that would benefit the main library and would have made your work easier.

Also thanks for the bug reports.

I didn't know about the xregexp issue, and will investigate next week.

The other problem with `arguments` is that neith is currently written in a slightly older version of Khepri, 0.1X, and the syntax for argument access changed in V1. Just add a `-` before the argument list to bind the arguments object itself:

```
\ops(...) ->
        reduceRight(ops, and);
```

should be:

```
\-ops(...) ->
        reduceRight(ops, and);
```

otherwise it treats `ops` as the first argument instead of as the argument object. I'll open a bug to track updating to use the most recent version of the language.

Also if you have a chance, please let me know what you found annoying about Khepri array notation as I'm always looking for ways to improve the language. The array literal notation should work fine, except you can't have trailing commas on the elements or empty elements. The array access notation had to be changed to use the dot operator instead.

```
arr[index]
```

becomes

```
arr.(index)
```

Good luck with the rest of your project.

**Comment by refset** [comment]
`arr.(index)` - aha, that's exactly what I was looking for! Messing with object descriptors feels sinful, but I did it as a result of my bad interpretation of [this probably unrelated comment](https://github.com/mattbierner/khepri/wiki/Other-Differences-From-ECMAScript#object-literal-getters-and-setter-syntax) in the wiki.

I'll be sure to keep you posted.
